-- Ejercicio 2 DDL | Diego Puértolas Ruiz 1SW

CREATE TABLE MONTADORES (
    Nif VARCHAR2(8) CONSTRAINT PK_MONTADORES PRIMARY KEY,
    Nombre VARCHAR2(20),
    Direccion VARCHAR2(50),
    Telefono NUMBER(9)
);

CREATE TABLE MODELOS (
    Codigo VARCHAR2(5) CONSTRAINT PK_MODELOS PRIMARY KEY,
    Nombre VARCHAR2(20)
);

CREATE TABLE CLIENTES (
    Nif VARCHAR2(8) CONSTRAINT PK_CLIENTES PRIMARY KEY,
    Nombre VARCHAR2(20),
    Direccion VARCHAR2(50),
    Telefono NUMBER(9)
);

CREATE TABLE MONTAJES (
    Nif VARCHAR2(8) CONSTRAINT FK_MONTAJES_MONTADORES REFERENCES MONTADORES(Nif),
    Codigo VARCHAR2(5) CONSTRAINT FK_MONTAJES_MODELOS REFERENCES MODELOS(Codigo),
    Fecha DATE
);

CREATE TABLE COMPRAS (
    Nif VARCHAR2(8) CONSTRAINT FK_COMPRAS_CLIENTES REFERENCES CLIENTES(Nif),
    Codigo VARCHAR2(5) CONSTRAINT FK_COMPRAS_MODELOS REFERENCES MODELOS(Codigo),
    Fecha DATE
);


-- Añado las FOREIGN KEY en la tabla MONTAJE:
    ALTER TABLE MONTAJES ADD CONSTRAINT FK_MONTAJES_MONTADORES FOREIGN KEY (Nif) REFERENCES MONTADORES(Nif);
    ALTER TABLE MONTAJES ADD CONSTRAINT FK_MONTAJES_MODELOS FOREIGN KEY (Codigo) REFERENCES MODELOS(Codigo);

-- FOREIGN KEY en la tabla COMPRAS:
    ALTER TABLE COMPRAS ADD CONSTRAINT FK_COMPRAS_CLIENTES FOREIGN KEY (Nif) REFERENCES CLIENTES(Nif);
    ALTER TABLE COMPRAS ADD CONSTRAINT FK_COMPRAS_MODELOS FOREIGN KEY (Codigo) REFERENCES MODELOS(Codigo);
