-- Clase 11
-- Diego Puértolas Ruiz, 1SW

-- 1-ELABORE UNA CONSULTA QUE LISTE NOMBRE DEL TRABAJO Y EL SALARIO DE LOS EMPLEADOS QUE SON MANAGER, 
-- CUYO CÓDIGO ES 100 O 125 Y CUYO SALARIO SEA MAYOR DE 6000.
SELECT 
  J.job_title,
  EMP.salary
FROM JOBS J
  INNER JOIN EMPLOYEES EMP
  ON J.job_id = EMP.job_id
  INNER JOIN DEPARTMENTS D
  ON EMP.employee_id = D.manager_id
WHERE D.manager_id IN (100, 125) AND EMP.salary > 6000;

-- 2-DESARROLLE UNA CONSULTA QUE LISTE EL CÓDIGO DE LA LOCALIDAD, LA CIUDAD Y EL NOMBRE DEL DEPARTAMENTO DE ÚNICAMENTE DE LOS
-- QUE SE ENCUENTRAN FUERA DE ESTADOS UNIDOS (US).
SELECT 
  L.location_id,
  L.city,
  D.department_name
FROM LOCATIONS L
  INNER JOIN DEPARTMENTS D
  ON L.location_id = D.location_id
  INNER JOIN COUNTRIES C
  ON L.country_id = C.country_id
WHERE L.country_id <> 'US';

-- 3-REALICE UNA CONSULTA QUE MUESTRES EL CÓDIGO DE LA REGIÓN, 
-- NOMBRE DE LA REGIÓN Y EL NOMBRE DE LOS PAÍSES QUE SE ENCUENTRAN EN “ASIA”.
SELECT
  R.region_id,
  R.region_name,
  C.country_name
FROM REGIONS R
  INNER JOIN COUNTRIES C
  ON R.region_id = C.region_id
WHERE R.region_name = 'Asia';

-- 4-DESARROLLE UNA CONSULTA DONDE MUESTRE EL CÓDIGO DE REGIÓN 
-- CON UN ALIAS "REGIÓN", EL NOMBRE DE LA REGIÓN CON UN ALIAS"NOMBRE REGIÓN",
-- QUE MUESTRE UNA CADENA STRING (CONCATENACIÓN) QUE DIGA LA SIGUIENTE FRASE 
-- “CÓDIGO PAÍS: CA NOMBRE: CANADÁ “,CA ES EL CÓDIGO DE PAÍS Y CANADÁ ES EL
-- NOMBRE DEL PAÍS, EL CÓDIGO DE LOCALIZACIÓN CON ALIAS "LOCALIZACIÓN", 
-- LA DIRECCIÓN DE CALLE CON ALIAS "DIRECCIÓN" Y EL CÓDIGO POSTAL CON 
-- ALIAS “CÓDIGO POSTAL”,ESTO A SU VEZ NO DEBEN APARECER CÓDIGO POSTAL 
-- QUE SEAN NULOS.
SELECT 
  R.region_id AS "REGIÓN",
  R.region_name AS "NOMBRE REGIÓN",
  'CODIGO PAIS :' || C.COUNTRY_ID || ' NOMBRE :' || C.COUNTRY_NAME AS "PAIS",
  L.location_id AS "LOCALIZACIÓN",
  L.street_address AS "DIRECCIÓN",
  L.postal_code AS "CÓDIGO POSTAL"
FROM hr.REGIONS R
  INNER JOIN hr.COUNTRIES C
  ON R.region_id = C.region_id
  INNER JOIN hr.LOCATIONS L
  ON C.country_id = L.country_id
WHERE L.postal_code IS NOT NULL;

-- 5-DESARROLLE UNA CONSULTA QUE MUESTRE EL NOMBRE DE LA REGIÓN, EL NOMBRE DEL PAÍS, EL ESTADO DE LA PROVINCIA, 
-- EL NOMBRE Y APELLIDO DE LOS EMPLEADOS QUE SON MANAGERS EN LOS PAÍSES DEL REINO UNIDO (UK) O
-- ESTADOS UNIDOS DE AMÉRICA (US) Y RESPECTIVAMENTE DE LOS ESTADOS DE LA PROVINCIA DE OXFORD Y WASHINGTON.
SELECT 
  R.region_name,
  C.country_name,
  L.state_province,
  EMP.first_name,
  EMP.last_name
FROM REGIONS R
  INNER JOIN COUNTRIES C
  ON R.region_id = C.region_id
  INNER JOIN LOCATIONS L
  ON C.country_id = L.country_id
  INNER JOIN DEPARTMENTS D
  ON L.location_id = D.location_id
  INNER JOIN EMPLOYEES EMP
  ON D.manager_id = EMP.employee_id
WHERE (C.country_id IN ('UK', 'US') AND L.state_province IN ('Oxford', 'Washington'));