-- CLASE 2
-- Diego Puértolas Ruiz 1SW

-- 1-MUESTRA NOMBRE, APELLIDOS, SALARIO Y SALARIO MÁS UN PLUS DE 1000 PARA TODOS LOS EMPLEADOS.
SELECT first_name, last_name, salary, salary + 1000 AS salario_plus FROM EMPLOYEES;

-- 2-Misma consulta anterior, añadiendo una nueva columna en la que muestre un campo con el contenido 'SALARIO AUMENTADO'
SELECT first_name, last_name, salary, salary + 1000, 'SALARIO AUMENTADO' FROM EMPLOYEES;

-- 3-Muestra el nombre de los trabajos que tienen un salario maximo=10000
SELECT job_title FROM JOBS WHERE max_salary = 10000;

-- 4-MUESTRA NOMBRE Y APELLIDOS DE LOS EMPLEADOS QUE TENGAN UN SALARIO=10000 Y NO TENGAN COMISION PCT
SELECT first_name, last_name FROM EMPLOYEES WHERE salary = 10000 AND commission_pct IS NULL;

-- 5-MUESTRA EL CAMPO JOB_ID DEL TRABAJO DENOMINADO 'ACCOUNTANT' PERO CUYO SALARIO ESTABLECIDO ESTÉ ENTRE SALARIO MIN 5000 Y SALARIO MAX 15000
SELECT job_id FROM JOBS WHERE job_title = 'ACCOUNTANT' AND min_salary >= 5000 AND max_salary <= 15000;

-- 6a-MUESTRA EL CAMPO JOB_ID PARA EL QUE SU TRABAJO SE DENOMINE 'ACCOUNTANT' O QUE SU SALARIO MINIMO ESTABLECIDO SEA MENOR DE 5000 O SU SALARIO MAX SEA MAYOR QUE 15000
SELECT job_id FROM JOBS WHERE job_title = 'ACCOUNTANT' OR min_salary < 5000 OR max_salary > 15000;

-- 6b-MUESTRA EL CAMPO JOB_ID PARA EL QUE SU TRABAJO SE DENOMINE 'ACCOUNTANT' O QUE SU SALARIO MINIMO ESTABLECIDO SEA MAYOR DE 5000 Y SU SALARIO MAX SEA MENOR QUE 15000
SELECT job_id FROM JOBS WHERE job_title = 'ACCOUNTANT' OR (min_salary > 5000 AND max_salary > 15000);

-- 7a-MUESTRA LOS EMPLEADOS CONTRATADOS (HIRE_DATE)DESPUES DEL 2005.
SELECT first_name, last_name FROM EMPLOYEES WHERE hire_date > '31/12/2005';

-- 7b-MUESTRA LOS EMPLEADOS CONTRATADOS EN MAYO DEL 2007(HIRE_DATE)
SELECT first_name, last_name FROM EMPLOYEES WHERE hire_date >= '1/5/2007' AND hire_date <= '31/5/2007';
SELECT first_name, last_name FROM EMPLOYEES WHERE hire_date BETWEEN '1/5/2007' AND '31/5/2007';

-- 8-MOSTRAR LOS EMPLEADOS ORDENADOS POR ORDEN ALFABETICO ASCENDENTE
SELECT first_name, last_name FROM EMPLOYEES ORDER BY last_name ASC;

-- 9-MUESTRA LOS EMPLEADOS ORDENADOS PRIMERO POR FECHA DE CONTRATACION Y LUEGO POR SALARIO
SELECT * FROM EMPLOYEES ORDER BY hire_date, salary;

-- 10-MUESTRA LOS EMPLEADOS NO CONTRATADOS EN EL AÑO 2007
SELECT * FROM EMPLOYEES WHERE hire_date < '1/1/2007' AND hire_date > '31/12/2007'; 
SELECT * FROM EMPLOYEES WHERE hire_date NOT BETWEEN '1/1/2007' AND '31/12/2007';