-- Clase 13 - Subconsultas
-- Diego Puértolas Ruiz, 1SW

-- HASTA AHORA:
SELECT CAMPO FROM TABLA;

-- PERO PODEMOS HACER:

--CONSULTAS SOBRE UNA CONSULTA
SELECT CAMPO FROM CONSULTA;

--CONSULTAS CON CONSULTAS EN EL FILTRADO
SELECT CAMPO FROM TABLA WHERE CAMPO CONDICION CONSULTA

--CONSULTAS DENTRO DEL SELECT O DEL ORDER BY
SELECT FIRST_NAME, LAST_NAME 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (
  SELECT DEPARTMENT_ID 
  FROM DEPARTMENTS 
  WHERE LOCATION_ID=2500
);

SELECT FIRST_NAME, LAST_NAME 
FROM EMPLOYEES 
WHERE (DEPARTMENT_ID, MANAGER_ID) IN (
  SELECT DEPARTMENT_ID, MANAGER_ID 
  FROM DEPARTMENTS 
  WHERE LOCATION_ID=2500
);

SELECT * FROM (SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES);

SELECT EMPLOYEE_ID 
FROM (
  SELECT EMPLOYEE_ID,DEPARTMENT_ID 
  FROM EMPLOYEES
  WHERE FIRST_NAME='Peter' AND LAST_NAME='Tucker'
);

-- CON ALIAS
SELECT SUB.EMPLOYEE_ID 
FROM (
  SELECT EMPLOYEE_ID,DEPARTMENT_ID 
  FROM EMPLOYEES
  WHERE FIRST_NAME='Peter' AND LAST_NAME='Tucker'
)SUB;

--ORDENAMOS POR UNA CONSULTA
SELECT EM.FIRST_NAME, EM.LAST_NAME
FROM EMPLOYEES EM
ORDER BY (
  SELECT DE.DEPARTMENT_NAME  
  FROM DEPARTMENTS DE
  WHERE EM.DEPARTMENT_ID = DE.DEPARTMENT_ID
);

--OTRO TIPO DE FILTRADO CON SUBCONSULTA
--EMPLEADOS EN ACTIVO CON MAS DE DOS EMPLEOS EN LA TABLA DE HISTORICO
SELECT E.EMPLOYEE_ID, E.LAST_NAME, E.JOB_ID
FROM EMPLOYEES E 
WHERE  2 <= (
  SELECT COUNT(*)
  FROM  JOB_HISTORY J
  WHERE  J.EMPLOYEE_ID = E.EMPLOYEE_ID
);

--OTRA FORMA DE HACER LO MISMO:
SELECT E.EMPLOYEE_ID, E.LAST_NAME,E.JOB_ID 
FROM 
  EMPLOYEES E 
  INNER JOIN JOB_HISTORY J
  ON J.EMPLOYEE_ID=E.EMPLOYEE_ID
GROUP BY 
  E.EMPLOYEE_ID, 
  E.LAST_NAME,
  E.JOB_ID
HAVING 
  COUNT(*)>=2;