-- Ejercicio 3 DDL | Diego Puértolas Ruiz 1SW

CREATE TABLE SOCIOS (
    Id_socio VARCHAR2(5) CONSTRAINT PK_SOCIOS PRIMARY KEY,
    Nombre VARCHAR2(20) CONSTRAINT NN_SOCIOS_Nombre NOT NULL,
    Telefono NUMBER(9) CONSTRAINT NN_SOCIOS_Telefono NOT NULL
);

CREATE TABLE ACTORES (
    Id_actor VARCHAR2(5) CONSTRAINT PK_ACTORES PRIMARY KEY,
    Nombre VARCHAR2(20) CONSTRAINT NN_ACTORES_Nombre NOT NULL
);

CREATE TABLE DIRECTORES (
    Id_director VARCHAR2(5) CONSTRAINT PK_DIRECTORES PRIMARY KEY,
    Nombre VARCHAR2(20) CONSTRAINT NN_DIRECTORES_Nombre NOT NULL,
    Nacionalidad VARCHAR2(40)
);

CREATE TABLE PELICULAS (
    Id_pelicula VARCHAR2(5) CONSTRAINT PK_PELICULAS PRIMARY KEY,
    Titulo VARCHAR2(50) CONSTRAINT NN_PELICULAS_Titulo NOT NULL,
    Id_director VARCHAR2(5)
);

CREATE TABLE INTERPRETAR (
    Id_pelicula VARCHAR2(5);
    Id_actor VARCHAR2(5)
);

CREATE TABLE EJEMPLARES (
    Id_ejemplar VARCHAR2(5) CONSTRAINT PK_EJEMPLARES PRIMARY KEY,
    Titulo VARCHAR2(50) CONSTRAINT NN_EJEMPLARES_Titulo NOT NULL,
    Id_pelicula VARCHAR2(5)
);

CREATE TABLE ALQUILAR (
    Fecha_compra DATE CONSTRAINT NN_ALQUILAR_Fecha_compra NOT NULL,
    Fecha_final DATE CONSTRAINT NN_ALQUILAR_Fecha_final NOT NULL,
    Id_ejemplar VARCHAR2(5),
    Id_socio VARCHAR2(5)
);

-- Añadimos las FOREIGN KEYS

-- FOREIGN KEY TABLA ALQUILAR
ALTER TABLE ALQUILAR ADD CONSTRAINT FK_ALQUILAR_EJEMPLARES FOREIGN KEY (Id_ejemplar) REFERENCES EJEMPLARES(Id_ejemplar);
ALTER TABLE ALQUILAR ADD CONSTRAINT FK_ALQUILAR_SOCIOS FOREIGN KEY (Id_socio) REFERENCES SOCIOS(Id_socio);

-- FOREIGN KEY TABLA EJEMPLARES 
ALTER TABLE EJEMPLARES ADD CONSTRAINT FK_EJEMPLARES_PELICULAS FOREIGN KEY (Id_pelicula) REFERENCES PELICULAS(Id_pelicula);

-- FOREIGN KEY TABLA PELICULAS
ALTER TABLE PELICULAS ADD CONSTRAINT FK_PELICULAS_DIRECTORES FOREIGN KEY (Id_director) REFERENCES DIRECTORES(Id_director);

-- FOREIGN KEY TABLA INTERPRETAR 
ALTER TABLE INTERPRETAR ADD CONSTRAINT FK_INTERPRETAR_PELICULAS FOREIGN KEY (Id_pelicula) REFERENCES PELICULAS(Id_pelicula);
ALTER TABLE INTERPRETAR ADD CONSTRAINT FK_INTERPRETAR_ACTORES FOREIGN KEY (Id_actor) REFERENCES ACTORES(Id_actor);