-- Ejercicio 7 DDL | Diego Puértolas Ruiz 1SW

CREATE TABLE CATEGORIAS (
  Tipo_categoria VARCHAR(20) CONSTRAINT PK_CATEGORIAS PRIMARY KEY,
  IVA NUMBER(2), 
  Descripcion VARCHAR2(100)
);

CREATE TABLE HOTELES (
  Id_hotel VARCHAR2(5) CONSTRAINT PK_HOTELES PRIMARY KEY,
  Nombre VARCHAR2(20),
  Direccion VARCHAR2(50),
  Telefono NUMBER(9),
  Anyo_construccion DATE,
  Tipo_categoria VARCHAR2(20)
);

CREATE TABLE HABITACIONES (
  Id_habitacion VARCHAR2(5) CONSTRAINT PK_HABITACIONES PRIMARY KEY,
  Tipo VARCHAR2(40),
  Id_hotel VARCHAR2(5)
);

CREATE TABLE PARTICULARES (
  Id_particular VARCHAR2(5) CONSTRAINT PK_PARTICULARES PRIMARY KEY, 
  Nombre VARCHAR2(20),
  Direccion VARCHAR2(50),
  Telefono NUMBER(9)
);

CREATE TABLE AGENCIAS (
  Id_agencia VARCHAR2(5) CONSTRAINT PK_AGENCIAS PRIMARY KEY, 
  Nombre VARCHAR2(20),
  Direccion VARCHAR2(50),
  Telefono NUMBER(9)
);

CREATE TABLE RESERVAS_PARTICULARES (
  Precio NUMBER(6,2),
  Fecha_inicio DATE,
  Fecha_final DATE,
  Id_habitacion VARCHAR2(5),
  Id_particular VARCHAR2(5)
);

CREATE TABLE RESERVAS_AGENCIAS (
  Precio NUMBER(6,2),
  Fecha_inicio DATE,
  Fecha_final DATE,
  Id_habitacion VARCHAR2(5),
  Id_agencia VARCHAR2(5)
);

-- Añado las FOREIGN KEYS

-- FOREIGN KEY de la TABLA HOTELES:
ALTER TABLE HOTELES ADD CONSTRAINT FK_HOTELES_CATEGORIAS FOREIGN KEY (Tipo_categoria) REFERENCES CATEGORIAS (Tipo_categoria);

-- FOREIGN KEY de la TABLA HABITACIONES:
ALTER TABLE HABITACIONES ADD CONSTRAINT FK_HABITACIONES_HOTELES FOREIGN KEY (Id_hotel) REFERENCES HOTELES (Id_hotel);

-- FOREIGN KEYS de la TABLA RESERVAS_PARTICULARES:
ALTER TABLE RESERVAS_PARTICULARES ADD CONSTRAINT FK_RESERVAS_PARTICULARES_HABITACIONES FOREIGN KEY (Id_habitacion) REFERENCES HABITACIONES (Id_habitacion);
ALTER TABLE RESERVAS_PARTICULARES ADD CONSTRAINT FK_RESERVAS_PARTICULARES_PARTICULARES FOREIGN KEY (Id_particular) REFERENCES PARTICULARES (Id_particular);

-- FOREIGN KEYS de la TABLA RESERVAS_AGENCIAS:
ALTER TABLE RESERVAS_AGENCIAS ADD CONSTRAINT FK_RESERVAS_AGENCIAS_HABITACIONES FOREIGN KEY (Id_habitacion) REFERENCES HABITACIONES (Id_habitacion);
ALTER TABLE RESERVAS_AGENCIAS ADD CONSTRAINT FK_RESERVAS_AGENCIAS_AGENCIAS FOREIGN KEY (Id_agencia) REFERENCES AGENCIAS (Id_agencia);