-- Ejercicio 6 DDL | Diego Puértolas Ruiz 1SW

CREATE TABLE PACIENTES (
  Id_paciente VARCHAR2(5) CONSTRAINT PK_PACIENTES PRIMARY KEY,
  Nombre VARCHAR2(20),
  Apellidos VARCHAR2(50),
  Direccion VARCHAR2(100),
  Poblacion NUMBER(9),
  Provincia VARCHAR2(20),
  Cod_postal NUMBER(5),
  Telefono NUMBER(9),
  Fecha_nacimiento DATE
);

CREATE TABLE MEDICOS (
  Id_medico VARCHAR2(5) CONSRTRAINT PK_MEDICOS PRIMARY KEY,
  Nombre VARCHAR2(20),
  Apellidos VARCHAR2(50),
  Telefono NUMBER(9),
  Especialidad VARCHAR2(30)
);

CREATE TABLE INGRESOS (
  Id_ingreso VARCHAR2(5) CONSRTRAINT PK_INGRESOS PRIMARY KEY,
  Num_habitacion NUMBER(4),
  Cama NUMBER(5),
  Fecha_ingreso DATE,
  Id_paciente VARCHAR2(5),
  Id_medico VARCHAR2(5)
),

-- Añado las FOREIGN KEYS:

-- FOREIGN KEYS TABLA INGRESOS
ALTER TABLE INGRESOS ADD CONSRTRAINT FK_INGRESOS_PACIENTES FOREIGN KEY (Id_paciente) REFERENCES PACIENTES (Id_paciente);
ALTER TABLE INGRESOS ADD CONSRTRAINT FK_INGRESOS_MEDICOS FOREIGN KEY (Id_medico) REFERENCES MEDICOS (Id_medico);
