-- Ejercicio 5 DDL | Diego Puértolas Ruiz 1SW

CREATE TABLE EDITORIALES (
  Id_editorial VARCHAR2(5) CONSTRAINT PK_EDITORIALES PRIMARY KEY,
  Nombre VARCHAR2(20) 
);

CREATE TABLE PERIODISTAS (
  Id_periodista VARCHAR2(5) CONSTRAINT PK_PERIODISTAS PRIMARY KEY,
  Nombre VARCHAR2(20),
  Apellidos VARCHAR2(40), 
  DNI VARCHAR2(20),
  Nombre VARCHAR2(20),
  Nombre VARCHAR2(20),
  Id_editorial VARCHAR2(5)
);

CREATE TABLE ARTICULOS (
  Id_articulo VARCHAR2(5) CONSTRAINT PK_ARTICULOS PRIMARY KEY,
  Titulo VARCHAR2(40),
  Id_periodista VARCHAR2(5),
  Numero NUMBER(5)
);

CREATE TABLE NUMEROS (
  Numero NUMBER(5) CONSTRAINT PK_NUMEROS PRIMARY KEY,
  Fecha DATE, 
  Paginas NUMBER(100),
  Ejemplares NUMBER(1000),
  Num_registro NUMBER(5)
);

CREATE TABLE REVISTAS (
  Num_registro NUMBER(5) CONSTRAINT PK_REVISTAS PRIMARY KEY,
  Titulo VARCHAR2(40),
  Periodicidad DATE,
  Tipo VARCHAR2(10),
  Cod_sucursal VARCHAR2(5)
)

CREATE TABLE SUCURSALES (
  Cod_sucursal VARCHAR2(5) CONSTRAINT PK_SUCURSALES PRIMARY KEY,
  Domicilio VARCHAR2(20),
  Telefono NUMBER(9),
  Id_editorial VARCHAR2(5)
);
 
CREATE TABLE EMPLEADOS (
  Id_empleado VARCHAR2(5) CONSTRAINT PK_EMPLEADOS PRIMARY KEY,
  Nombre VARCHAR2(20),
  Apellidos VARCHAR2(20),
  DNI VARCHAR2(9),
  Telefono NUMBER(9),
  Cod_sucursal VARCHAR2(5)
);

-- Añadimos las FOREIGN KEYS

-- FOREIGN KEY TABLA PERIODISTAS:
ALTER TABLE PERIODISTAS ADD CONSTRAINT FK_PERIODISTAS_EDITORIALES FOREIGN KEY (Id_editorial) REFERENCES EDITORIALES (Id_editorial);

-- FOREIGN KEYS TABLA ARTICULOS:
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_PERIODIOSTAS FOREIGN KEY (Id_periodista) REFERENCES PERIODISTAS (Id_periodista);
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_NUMEROS FOREIGN KEY (Numero) REFERENCES NUMEROS (Numero);

-- FOREIGN KEY TABLA NUMEROS:
ALTER TABLE NUMEROS ADD CONSTRAINT FK_NUMEROS_REVISTAS FOREIGN KEY (Num_registro) REFERENCES REVISTAS (Num_registro);

-- FOREIGN KEY TABLA REVISTAS:
ALTER TABLE REVISTAS ADD CONSTRAINT FK_REVISTAS_SUCURSALES FOREIGN KEY (Cod_sucursal) REFERENCES SUCURSALES (Cod_sucursal);

-- FOREIGN KEY TABLA SUCURSALES:
ALTER TABLE SUCURSALES ADD CONSTRAINT FK_SUCURSALES_EDITORIALES FOREIGN KEY (Id_editorial) REFERENCES EDITORIALES (Id_editorial);

-- FOREIGN KEY TABLA EMPLEADOS:
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS_SUCURSALES FOREIGN KEY (Cod_sucursal) REFERENCES SUCURSALES (Cod_sucursal); 
