-- Ejercicio 1 DDL | Diego Puértolas Ruiz 1SW

CREATE TABLE REGIONES (
  Id_region VARCHAR2(5) CONSTRAINT PK_REGIONES PRIMARY KEY,
  Nombre VARCHAR2(20)
);

CREATE TABLE PROVINCIAS (
  Id_provincia VARCHAR2(5) CONSTRAINT PK_PROVINCIAS PRIMARY KEY,
  Nombre VARCHAR2(20),
  Id_region VARCHAR2(5)
)

CREATE TABLE LOCALIDADES (
  Id_localidad VARCHAR2(5) CONSTRAINT PK_LOCALIDADES PRIMARY KEY,
  Nombre VARCHAR2(20),
  Id_provincia VARCHAR2(5)
);

CREATE TABLE EMPLEADOS (
  Id_empleado VARCHAR2(5) CONSTRAINT PK_EMPLEADOS PRIMARY KEY,
  Nombre VARCHAR2(20),
  Apellidos VARCHAR2(40),
  Id_localidad VARCHAR2(5)
);

-- Añadimos las FOREIGN KEYS

-- FOREIGN KEY TABLA PROVINCIAS
ALTER TABLE PROVINCIAS ADD CONSTRAINT FK_PROVINCIAS_REGIONES FOREIGN KEY (Id_region) REFERENCES REGIONES(Id_region);

-- FOREIGN KEY TABLA LOCALIDADES
ALTER TABLE LOCALIDADES ADD CONSTRAINT FK_LOCALIDADES_PROVINCIAS FOREIGN KEY (Id_provincia) REFERENCES PROVINCIAS(Id_provincia);

-- FOREIGN KEY TABLA EMPLEADOS
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS_LOCALIDADES FOREIGN KEY (Id_localidad) REFERENCES LOCALIDADES(Id_localidad);