-- Clase 9
-- Diego Puértolas Ruiz, 1SW

-- 1-MUESTRA EL NOMBRE, APELLIDOS Y NOMBRE DEL DEPARTAMENTO DE LOS EMPLEADOS.
SELECT 
  EMP.first_name,
  EMP.last_name,
  D.department_name
FROM EMPLOYEES EMP
  INNER JOIN DEPARTMENTS D
  ON EMP.department_id = D.department_id;

-- 2-MUESTRA EL NOMBRE, APELLIDOS Y NOMBRE DEL DEPARTAMENTO DE TODOS LOS EMPLEADOS.
SELECT
  EMP.first_name, 
  EMP.last_name,
  D.department_name
FROM EMPLOYEES EMP
  LEFT JOIN DEPARTMENTS D
  ON EMP.department_id = D.department_id;

-- 3-MUESTRA TODOS LOS NOMBRES DE DEPARTAMENTOS, EL NOMBRE Y APELLIDOS DE LOS EMPLEADOS DE DICHOS DEPARTAMENTOS.
SELECT 
  D.department_name,
  EMP.first_name,
  EMP.last_name
FROM DEPARTMENTS D
  LEFT JOIN EMPLOYEES EMP
  ON D.department_id = EMP.department_id;

-- 4-MOSTRAR LOS DEPARTAMENTOS QUE NO TIENEN EMPLEADOS.
SELECT 
  D.department_name
FROM DEPARTMENTS D
  LEFT JOIN EMPLOYEES EMP
  ON D.department_id = EMP.department_id
WHERE EMP.employee_id IS NULL;

-- 5-MOSTRAR NOMBRE Y APELLIDOS DE LOS EMPLEADOS Y EL NOMBRE DEL TRABAJO QUE DESEMPEÑAN
SELECT 
  EMP.first_name,
  EMP.last_name,
  J.job_title
FROM EMPLOYEES EMP
  INNER JOIN JOBS J
  ON EMP.job_id = J.job_id;

-- 6-MUESTRA EL NOMBRE DE LAS CIUDADES QUE TIENEN DEPARTAMENTOS.
SELECT 
  L.city
FROM LOCATIONS L
  INNER JOIN DEPARTMENTS D
  ON L.location_id = D.location_id;

-- 7- REPITE EL EJERCICIO ANTERIOR PERO MUESTRA LOS RESULTADOS DE LAS CIUDADES SIN REPETIR.
SELECT 
  L.city
FROM LOCATIONS L
  INNER JOIN DEPARTMENTS D
  ON L.location_id = D.location_id
GROUP BY L.city;

-- 8-MUESTRA EL NOMBRE, APELLIDOS, NOMBRE DE DEPARTAMENTO Y CIUDAD DE LOS EMPLEADOS
SELECT 
  EMP.first_name,
  EMP.last_name,
  D.department_name,
  L.city
FROM EMPLOYEES EMP
  INNER JOIN DEPARTMENTS D
  ON EMP.department_id = D.department_id
  INNER JOIN LOCATIONS L
  ON D.location_id = L.location_id;

-- 9-MUESTRA EL NOMBRE, APELLIDOS, NOMBRE DE DEPARTAMENTO Y CIUDAD DE TODOS LOS EMPLEADOS
SELECT 
  EMP.first_name,
  EMP.last_name,
  D.department_name,
  L.city
FROM EMPLOYEES EMP
  LEFT JOIN DEPARTMENTS D
  ON EMP.department_id = D.department_id
  LEFT JOIN LOCATIONS L
  ON D.location_id = L.location_id;

-- 9-MOSTRAR NOMBRE, APELLIDOS, NOMBRE DEL TRABAJO, FECHA DE INICIO Y FECHA FIN DE LOS TRABAJOS ANTERIORES DE LOS EMPLEADOS
SELECT
  EMP.first_name,
  EMP.last_name,
  J.job_title,
  HIS.start_date,
  HIS.end_date
FROM EMPLOYEES EMP
  INNER JOIN JOBS J
  ON EMP.job_id = J.job_id
  INNER JOIN JOB_HISTORY HIS
  ON EMP.employee_id = HIS.employee_id;

-- 10-MOSTRAR NOMBRE Y APELLIDOS DE LOS EMPLEADOS QUE TRABAJAN EN UN DEPARTAMENTO LOCALIZADO EN LONDON.
SELECT 
  EMP.first_name,
  EMP.last_name
FROM EMPLOYEES EMP
  INNER JOIN DEPARTMENTS D
  ON EMP.department_id = D.department_id
  INNER JOIN LOCATIONS L
  ON D.location_id = L.location_id
WHERE L.city = 'London';

-- 11-MOSTRAR TODOS LOS NOMBRES DE DEPARTAMENTOS Y LOS NOMBRES DE SUS REGIONES (CONTINENTES)
SELECT 
  D.department_name,
  R.region_name
FROM DEPARTMENTS D
  LEFT JOIN LOCATIONS L
  ON D.location_id = L.location_id
  LEFT JOIN COUNTRIES C
  ON L.country_id = C.country_id
  LEFT JOIN REGIONS R 
  ON C.region_id = R.region_id;

-- 12-MOSTRAR EL NOMBRE DE LOS DEPARTAMENTOS QUE TIENEN EMPLEADOS ASÍ COMO EL SALARIO DE ESTOS.
SELECT 
  D.department_name,
  EMP.salary
FROM DEPARTMENTS D
  INNER JOIN EMPLOYEES EMP
  ON D.department_id = EMP.department_id;