-- ABS()-> VALOR ABSOLUTO
-- ROUND(N,D)->REDONDEAR
-- TRUNC(N,D) ->TRUNCAR
-- MOD(X,Y)->RESTO, RESIDUO DE LA DIVISIÓN X/Y
-- POWER(X,Y) ->POTENCIA X ELEVADO A Y
-- SQRT(X)-> RAIZ CUADRADA

-- 1-Calcular el valor absoluto de -3
SELECT ABS(-3) AS absolute_value 
FROM DUAL;

-- 2-REDONDEA EL SALARIO INCREMENTADO EL 17% DE LOS EMPLEADOS A UN DECIMAL.
SELECT first_name, last_name, salary, ROUND(salary * 1.17, 1) AS increased_salary_rounded
FROM EMPLOYEES;

-- 3-MUESTRA EL RESIDUO DE LA DIVISIÓN DE 15/7
SELECT MOD(15, 7) AS residue 
FROM DUAL;

-- 4-CALCULA 3 ELEVADO A 7.
SELECT POWER(3, 7) AS powe_value
FROM DUAL;

-- 5-CALCULA LA RAIZ CUADRADA DE 144.
SELECT SQRT(144) AS square_root
FROM DUAL;

-- 6-TRUNCA EL SALARIO INCREMENTADO EL 17% DE LOS EMPLEADOS A UN DECIMAL.
SELECT first_name, last_name, salary, TRUNC(salary * 1.17, 1) AS increased_salary_truncated
FROM EMPLOYEES;