-- CLASE 1
-- Diego Puértolas Ruiz 1SW

-- Ejercicios consultas con filtros con operadores.

-- 1-MUESTRA EL CP DE LA CIUDAD DE ROMA
SELECT postal_code FROM LOCATIONS WHERE city = 'Roma';

-- 2-NOMBRE del DEPARTAMENTO con DEPARTMENT_ID=100
SELECT department_name FROM DEPARTMENTS WHERE department_id = 100;

-- 3-NOMBRE Y APELLIDOS DE LOS EMPLEADOS CONTRATADOS EL 1 DE ENERO DE 2007
SELECT first_name, last_name FROM EMPLOYEES WHERE hire_date = '1/1/2007';

-- 4-NOMBRE DE LOS TRABAJOS CUYO SALARIO MINIMO ES MAYOR QUE 10.000
SELECT job_title FROM JOBS WHERE min_salary > 10000;

-- 5-DEL HISTORICO DE TRABAJOS, MUESTRA EL DEL EMPLEADO CUYO EMPLOYEE_ID=100;
SELECT start_date, end_date FROM JOB_HISTORY WHERE employee_id = 100;

-- 6-NOMBRE Y APELLIDOS DE LOS EMPLEADOS CUYO MANAGER_ID NO SEA EL EMPLOYEE_ID=100
SELECT first_name, last_name FROM EMPLOYEES WHERE manager_id != 100;

-- 7-MUESTRA LA DIRECCION DE LOS DEPARTAMENTOS SITUADOS EN CALIFORNIA
SELECT street_address FROM LOCATIONS WHERE state_province = 'California';

-- 8-MUESTRA LAS CIUDADES DEL ESTADO DE TEXAS
SELECT city FROM LOCATIONS WHERE state_province = 'Texas';

-- 9-MUESTRA EL NOMBRE Y APELLIDOS DE LOS EMPLEADOS QUE NO TIENE MANAGER_ID
SELECT first_name, last_name FROM EMPLOYEES WHERE manaager_id IS NULL;

-- 10-MUESTRA EL NOMBRE Y APELLIDOS DE LOS EMPLEADOS QUE NO TIENEN COMISSION_PCT
SELECT first_name, last_name FROM EMPLOYEES WHERE commission_pct IS NULL;