-- Ejercicio 4 DDL | Diego Puértolas Ruiz 1SW

CREATE TABLE USUARIOS (
  Id_usuario VARCHAR2(5) CONSTRAINT PK_USUARIOS PRIMARY KEY,
  Nombre VARCHAR2(20) CONSTRAINT NN_USUARIOS_Nombre NOT NULL,
  Email VARCHAR2(40) CONSTRAINT NN_USUARIOS_Email NOT NULL,
  Contrasenya VARCHAR2(16) CONSTRAINT NN_USUARIOS_Contrasenya NOT NULL
);

CREATE TABLE VIDEOS (
  Id_video VARCHAR2(5) CONSTRAINT PK_USUARIOS PRIMARY KEY,
  Titulo VARCHAR2(50) CONSTRAINT NN_VIDEOS_Titulo NOT NULL,
  Duracion NUMBER(10000,2),
  Fecha DATE CONSTRAINT NN_VIDEOS_Fecha NOT NULL,
  Id_usuario VARCHAR(5),
  Id_clasificacion VARCHAR2(5)
);

CREATE TABLE CLASIFICACIONES (
  Id_clasificacion VARCHAR2(5) CONSTRAINT PK_CLASIFICACIONES,
  Nombre VARCHAR2(20) CONSTRAINT NN_CLASIFICACIONES_Nombre NOT NULL
)

CREATE TABLE VISUALIZAR (
  Duracion NUMBER(10000,2),
  Hora NUMBER(100),
  Fecha DATE CONSTRAINT NN_VISUALIZAR_Fecha NOT NULL,
  Id_usuario VARCHAR2(5),
  Id_video VARCHAR2(5)
)

CREATE TABLE FAVORITOS (
  Fecha DATE CONSTRAINT NN_FAVORITOS_Fecha NOT NULL,
  Id_usuario VARCHAR2(5),
  Id_video VARCHAR2(5)
)

-- Añadimos las FOREIGN KEYS

-- FOREIGN KEYS TABLA VIDEOS:
ALTER TABLE VIDEOS ADD CONSTRAINT FK_VIDEOS_USUARIOS FOREIGN KEY (Id_usuario) REFERENCES USUARIOS (Id_video);
AlTER TABLE VIDEOS ADD CONSTRAINT FK_VIDEOS_CLASIFICACIONES FOREIGN KEY (Id_clasificacion) REFERENCES CLASIFICACIONES (Id_clasificacion);

-- FOREIGN KEYS TABLA VISUALIZAR:
ALTER TABLE VISUALIZAR ADD CONSTRAINT FK_VISUALIZAR_VIDEOS FOREIGN KEY (Id_video) REFERENCES VIDEOS (Id_video);
ALTER TABLE VISUALIZAR ADD CONSTRAINT FK_VISUALIZAR_USUARIOS FOREIGN KEY (Id_usuario) REFERENCES USUARIOS (Id_usuario);

-- FOREIGN KEYS TABLA FAVORITOS:
ALTER TABLE FAVORITOS ADD CONSTRAINT FK_FAVORITOS_USUARIOS FOREIGN KEY (Id_usuario) REFERENCES USUARIOS (Id_usuario);
ALTER TABLE FAVORITOS ADD CONSTRAINT FK_FAVORITOS_VIDEOS FOREIGN KEY (Id_video) REFERENCES VIDEOS (Id_video);
